### ISSUE TITLE
How to get the right value of domian_list ?

### ISSUE THREAD

**Issue by simple4sd** [felixwilhelm/xenpwn#1]
The code location is xentrace.cc : 267, as follows:
`addr_t domain_list = 0xffff82d0802ce100;  // Xen 4.5  Ubuntu`
`// 0xffff82d0802d6198; // SLES XEN`

I try the two value listed in the source code, but they both can't work.
 I'm sorry to ask how can I get the right value in current environment ?
 (My host OS is Suse Leap 42.1 with Xen 4.5.1)

**Comment by felixwilhelm** [comment]
Hey,
good catch, I should probably document this.
The easiest way to get this value is to open the (non-stripped) ELF binary of your Xen hypervisor with GDB and just print the address of the domain_list structure:
```
felix@knife ~ % gdb xen-syms
(gdb) print &domain_list
$1 = (struct domain **) 0xffff82c48028e0a8 <domain_list>
```

How to get access to a non stripped Xen binary depends on the distribution and package manager used. In the worst case you might be required to build the hypervisor yourself. 

Hope that helps :)
